#!/usr/bin/tclsh

set pid [ lrange $argv 0 0 ]

proc get_parent_pid {pid} {
  set f [ open "|grep PPid /proc/$pid/status" ]
  set l [ gets $f ]
  close $f
  scan $l "%s %d" lit parent
  return $parent
}

set pattern {[0-9]}
set children ""
foreach f [ glob /proc/$pattern* ] {
  set f [ file tail $f ]
  set parent [ get_parent_pid $f ]
    if { $parent == $pid } then {
      set children [ format "%s %s" $children $f ]
    }
}

puts [ get_parent_pid $pid ]
puts $children
