.TH TKPS 1 "July 4, 2001" "Debian Project" "Debian Manual"
.SH NAME
tkps \- process browser

.SH SYNOPSIS
Lists the running processes and allows sending signals

.SH DESCRIPTION
This script generates a process browser, which lists the running
processes (using unix "ps") and allows you to send signals (such as
KILL) using a popup menu.
.PP
Create a scrollbar on the right side of the main window and a listbox
on the left side.

.SH AUTHORS
Adapted/enhanced for Linux by Ed Petron (epetron@leba.net)
.br
Kidong Lee (kidong@shinbiro.com) May 1997
.PP
Originally written by Henry Minsky (hqm@ai.mit.edu) May 1994
.PP
This manual page was created by Andreas Tille <tille@debian.org> for
the Debian GNU/Linux system (but may be used by others).
